# Generated by Django 4.0.6 on 2022-11-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'capital_contact',
            },
        ),
    ]
